### ISSUE TITLE
Add response_to in comments

### ISSUE THREAD

**Issue by belst** [w0bm/mariadb-postgres-migration#5]
count leading `^` in comments and add comment to `response_to` field if available.

don't forget to check `deleted_at` column and don't skip deleted comments if they where deleted after the comment was written.

can't really do sth with edits though

**Comment by jkhsjdhjs** [comment]
In case multiple lines begin with `^`, only use the first line or don't fill the `response_to` field?

**Comment by belst** [comment]
yeah or the last or any. just define it somehow. first is probably ok
